package dev.mk.First.business.value;

public enum TrainingType {
    BASIC,
    QUALIFIED_FIRST_AID,
    TECHNICAL_RESCUE,
    ANTI_FLOOD_AND_WATER_RESCUE,
    MAINTENANCE_DRIVER_RESCUE_EQUIPMENT,
    LEADERS,
    HEADERS,
    COMMUNE_COMMANDER,
    LIFT,
    CHEM_ECO_RESCUE,
    SEARCH_AND_RESCUE,
    HIGH_ALTITUDE_RESCUE,
    LADDER,
    HELMSMAN,
    SAWMAN
}
